### ISSUE TITLE
Clients (Non-host) have lingering Engineer Mine AoE visual, even after the mine has disappeared.

### ISSUE THREAD

**Issue by Inzanity99** [egpimp/Eggs-Skills#1]
Here is a picture of what I mean with "visual":
https://imgur.com/a/3a7JzxF

This does not happen to the host. (it doesnt matter if the host or client is playing engineer)

We had the exact same mod setup, so its not a miss match on that part.

**Comment by egpimp** [comment]
If you get a chance can you mess with artificer shift I added see if it has the same problem at all?  It uses the same indicator prefab

**Comment by egpimp** [comment]
Also fixed, remembered to close
