### ISSUE TITLE
Suggestion - Add config options to disable individual skills

### ISSUE THREAD

**Issue by gaforb** [egpimp/Eggs-Skills#2]
When using other mods that also add skills some character loadouts can get very crowded, and being able to manage this would be great.

**Comment by gaforb** [comment]
I tried to make a fork or whatever but I don't quite understand github
Here's a basic draft of config code you should be able to just copypaste into the project
It goes in SkillsLoader.cs, replacing everything from setting huntress' characterbody ref to RegisterArtificerSkills()

        internal static GameObject huntressRef = UnityEngine.Resources.Load<GameObject>("prefabs/characterbodies/HuntressBody");

        internal static ConfigEntry<bool> EnableArtificerSkills { get; set; }
        internal static ConfigEntry<bool> EnableMercenarySkills { get; set; }
        internal static ConfigEntry<bool> EnableCommandoSkills { get; set; }
        internal static ConfigEntry<bool> EnableEngiSkills { get; set; }
        internal static ConfigEntry<bool> EnableAcridSkills { get; set; }
        internal static ConfigEntry<bool> EnableLoaderSkills { get; set; }
        internal static ConfigEntry<bool> EnableCaptainSkills { get; set; }
        internal static ConfigEntry<bool> EnableRexSkills { get; set; }
        internal static ConfigEntry<bool> EnableBanditSkills { get; set; }
        internal static ConfigEntry<bool> EnableHuntressSkills { get; set; }
        internal static ConfigEntry<bool> EnableMultSkills { get; set; }

        internal static List<SkillDef> defList = new List<SkillDef>();
        internal static List<Type> extraStates = new List<Type>();
        private void Awake()
        {
            Debug.Log("Thanks SOM for the icon work <3");
            Assets.LoadResources();
            InitConfig();
            UnlocksRegistering.RegisterUnlockables();
            RegisterSkills();
        }
        private void InitConfig()
        {
            string survivor = "Commando"
            base.EnableCommandoSkills = Config.Bind<bool>(survivor, "Add new skills for " + survivor, true, "Enable/Disable additional skills for " + survivor);
            string survivor = "Huntress"
            base.EnableHuntressSkills = Config.Bind<bool>(survivor, "Add new skills for " + survivor, true, "Enable/Disable additional skills for " + survivor);
            string survivor = "Bandit"
            base.EnableBanditSKills = Config.Bind<bool>(survivor, "Add new skills for " + survivor, true, "Enable/Disable additional skills for " + survivor);
            string survivor = "MUL-T"
            base.EnableMultSkills = Config.Bind<bool>(survivor, "Add new skills for " + survivor, true, "Enable/Disable additional skills for " + survivor);
            string survivor = "Engineer"
            base.EnableEngiSkills = Config.Bind<bool>(survivor, "Add new skills for " + survivor, true, "Enable/Disable additional skills for " + survivor);
            string survivor = "Artificer"
            base.EnableArtificerSkills = Config.Bind<bool>(survivor, "Add new skills for " + survivor, true, "Enable/Disable additional skills for " + survivor);
            string survivor = "Mercenary"
            base.EnableMercenarySkills = Config.Bind<bool>(survivor, "Add new skills for " + survivor, true, "Enable/Disable additional skills for " + survivor);
            string survivor = "REX"
            base.EnableRexSkills = Config.Bind<bool>(survivor, "Add new skills for " + survivor, true, "Enable/Disable additional skills for " + survivor);
            string survivor = "Loader"
            base.EnableLoaderSkills = Config.Bind<bool>(survivor, "Add new skills for " + survivor, true, "Enable/Disable additional skills for " + survivor);
            string survivor = "Acrid"
            base.EnableAcridSkills = Config.Bind<bool>(survivor, "Add new skills for " + survivor, true, "Enable/Disable additional skills for " + survivor);
            string survivor = "Captain"
            base.EnableCaptainSkills = Config.Bind<bool>(survivor, "Add new skills for " + survivor, true, "Enable/Disable additional skills for " + survivor);
        }
        private void RegisterSkills()
        {
            bool enableArtificer = base.EnableArtificerSkills.Value;
            if (enableArtificer) { RegisterArtificerSkills(); }
            
            bool enableMercenary = base.EnableMercenarySkills.Value;
            if (enableMercenary) { RegisterMercenarySkills(); }
           
            bool enableCommando = base.EnableCommandoSkills.Value;
            if (enableCommando) { RegisterCommandoSkills(); }
            
            bool enableEngi = base.EnableEngiSkills.Value;
            if (enableEngi) { RegisterEngiSkills(); }
           
            bool enableAcrid = base.EnableAcridSkills.Value;
            if (enableAcrid) { RegisterAcridSkills(); }
            
            bool enableLoader = base.EnableLoaderSkills.Value;
            if (enableLoader) { RegisterLoaderSkills(); }
            
            bool enableCaptain = base.EnableCaptainSkills.Value;
            if (enableCaptain) { RegisterCaptainSkills(); }
            
            bool enableRex = base.EnableRexSkills.Value;
            if (enableRex) { RegisterRexSkills(); }
            
            bool enableBandit = base.EnableBanditSkills.Value;
            if (enableBandit) { RegisterBanditSkills(); }
            
            bool enableHuntress = base.EnableHuntressSkills.Value
            if (enableHuntress) { RegisterHuntressSkills(); }
            
            bool enableMult = base.EnableMultSkills.Value;
            if (enableMult) { RegisterMultSkills(); }
            
            foreach(SkillDef def in defList)
            {
                LoadoutAPI.AddSkillDef(def);
                Debug.Log("Skill: " + def.skillName + " Registered");
            }
            foreach (Type skill in extraStates)
            {
                LoadoutAPI.AddSkill(skill);
            }
        }
`

**Comment by egpimp** [comment]
Ty for the help, I already know how to add it, just a combination of too lazy and lots of bug hunting taking priority, planning on adding it next patch

**Comment by gaforb** [comment]
Ah yeah I assumed you could do it, was just trying to save you the busywork of writing it all out.
Also latest version 2.0.6 generates its config in the risk of rain 2 directory, instead of in the profile directory when using R2ModMan

**Comment by egpimp** [comment]
Yea I've not messed at all with R2Modman so anything involving it is
foreign to me.  Does the config at least work as expected?
