### ISSUE TITLE
Artificer Teleport cooldown / buffs

### ISSUE THREAD

**Issue by gaforb** [egpimp/Eggs-Skills#3]
I think 12 seconds makes it too weak, especially since it needs the charge time as well. I understand making it match snapfreeze but getting to teleport around a bit more often is much powerful than potentially keeping an enemy constantly frozen. Lowering it to match Ion Surge's cooldown of 8 seems like a good buff (or including a config for the cooldown, if you feel like it.)

Also, it tends to get 'caught' if you're aiming even slightly downwards, which makes it a bit hard to aim. Would be good if the crosshair focused on the actual center of the teleport radius, instead of just above it

**Comment by gaforb** [comment]
Actually after a bit of testing it seems to get caught on artificer's model if aiming upward while moving forward as well, as well as in a few other scenarios.

**Comment by egpimp** [comment]
Feedback noted, and I've been trying to work on making the movement & aiming on it much more concise, but the two options for movement are either perfectly accurate teleport that can accidentally put you through walls, or clunkier version that will never put you in a wall

**Comment by egpimp** [comment]
Also fixed, finally remembering to close issue
