### ISSUE TITLE
The mod still targets Assembly-CSharp.dll

### ISSUE THREAD

**Issue by JohnEdwa** [egpimp/Eggs-Skills#5]
The DLC moved basically everything to RoR2.dll.

[EDIT] Specifically, it will only work if:

>Aaron: the old MMHook still works for the most part yeah
>Aaron: either if the old MMHook is still there or if the new MMHook loads before it does

**Comment by egpimp** [comment]
It was a reference I forgot to remove, it doesn't do anything so it's all good
